---
# Landing role defaults
landing_domain: "{{ domain }}"
landing_port: "443"
landing_web_root: "/var/www/{{ domain }}"
landing_admin_email: "{{ certbot_email }}"
site_content_repo: "{{ site_content_repo | default('https://github.com/dyne/conspire-site.git') }}"
site_content_version: "{{ site_content_version | default('master') }}"
